'use client';
import { useEffect,useMemo,useRef,useState } from 'react';
import { createPortal } from 'react-dom';
import { Search,Menu,X,ArrowUpRight,Play,ExternalLink,ChevronLeft,Wrench } from 'lucide-react';
import type { Category,Project,RoomImage,Hotspot,Settings } from '@/lib/types';
type PublicData={categories:Category[];projects:Project[];settings:Omit<Settings,'adminId'|'adminPasswordHash'>};
type ProjectImageFallback=Project&{coverImage?:string;thumbnail?:string;imageUrl?:string};
type HeroSlide={project:Project;image:RoomImage|null;url:string};
type ProductImageHotspot=Hotspot&{productImageUrl?:string;productImage?:string;thumbnail?:string;imageUrl?:string};
function heroImageUrl(project:Project,image?:RoomImage){const legacy=project as ProjectImageFallback;return image?.url?.trim()||legacy.coverImage?.trim()||legacy.thumbnail?.trim()||legacy.imageUrl?.trim()||''}
function productImageUrl(hotspot:Hotspot){const image=hotspot as ProductImageHotspot;return image.productImageUrl?.trim()||image.productImage?.trim()||image.thumbnail?.trim()||image.imageUrl?.trim()||''}
function cropPosition(hotspot:Hotspot){const clamp=(value:number)=>Math.max(18,Math.min(82,Number.isFinite(value)?value:50));return`${clamp(hotspot.x)}% ${clamp(hotspot.y)}%`}
function projectText(p:Project){return `${p.title} ${p.subtitle} ${p.eyebrow} ${p.images.map(i=>`${i.alt} ${i.hotspots.map(h=>`${h.name} ${h.brand} ${h.description}`).join(' ')}`).join(' ')}`.toLowerCase()}
function projectMood(p:Project){const text=projectText(p),rules:[string,string[]][]=[['호텔',['호텔']],['빈티지',['빈티지','vintage']],['북유럽',['북유럽','scandinavian']],['화이트',['화이트','white']],['모던',['모던','modern','스테인리스']],['미니멀',['미니멀','minimal']],['우드',['우드','wood','월넛','오크','다이닝']],['내추럴',['내추럴','natural','초록','베란다']]];return rules.find(([,keys])=>keys.some(k=>text.includes(k)))?.[0]||'내추럴'}
export default function Home(){const [data,setData]=useState<PublicData|null>(null);const [category,setCategory]=useState('all');const [query,setQuery]=useState('');const [selected,setSelected]=useState<Project|null>(null);const [mobile,setMobile]=useState(false);const [heroIndex,setHeroIndex]=useState(0);const touchStart=useRef<number|null>(null);
 useEffect(()=>{fetch('/api/public',{cache:'no-store'}).then(r=>r.json()).then(setData)},[]);
 useEffect(()=>{if(selected)window.scrollTo({top:0,left:0,behavior:'auto'})},[selected]);
 useEffect(()=>{if(category!=='all'&&data&&!data.categories.some(c=>c.id===category))setCategory('all')},[category,data]);
 const heroSlides=useMemo(()=>data?.projects.flatMap<HeroSlide>(project=>{const images=[...project.images].sort((a,b)=>a.order-b.order);if(images.length)return images.map(image=>({project,image,url:heroImageUrl(project,image)})).filter(slide=>Boolean(slide.url));const url=heroImageUrl(project);return url?[{project,image:null,url}]:[]}).slice(0,6)||[],[data]);
 useEffect(()=>{if(heroSlides.length<2)return;const timer=window.setInterval(()=>setHeroIndex(index=>(index+1)%heroSlides.length),6500);return()=>window.clearInterval(timer)},[heroSlides.length]);
 useEffect(()=>{if(heroIndex>=heroSlides.length)setHeroIndex(0)},[heroIndex,heroSlides.length]);
 const filtered=useMemo(()=>data?.projects.filter(p=>(category==='all'||p.categoryId===category)&&(!query||projectText(p).includes(query.toLowerCase())))||[],[data,category,query]);
 if(!data)return <div className="loading"><span></span><p>공간을 준비하고 있습니다</p></div>;
 const heroTitle=data.settings.heroTitle==='마음에 드는 공간을 둘러보고'?'공간을 먼저 보고,\n가구를 발견하세요':data.settings.heroTitle;
 if(data.settings.serviceStatus==='maintenance')return <div className="status-screen"><Brand s={data.settings}/><div className="status-mark"><Wrench/></div><span>서비스 점검</span><h1>현재 사이트 점검 중입니다.</h1><p>더 나은 공간 경험을 위해 잠시 정비하고 있습니다.<br/>빠른 시일 내에 다시 찾아뵙겠습니다.</p></div>;
 if(selected)return <Detail project={selected} category={data.categories.find(c=>c.id===selected.categoryId)?.name||'미분류'} settings={data.settings} back={()=>setSelected(null)}/>;
 return <div className="site"><header><Brand s={data.settings}/><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="공간이나 제품을 검색해보세요"/>{query&&<button onClick={()=>setQuery('')}><X size={16}/></button>}</div><nav><a href="#projects">공간 둘러보기</a><a href="#about">소개</a></nav><button className="mobile-menu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header>{mobile&&<div className="mobile-nav"><a href="#projects">공간 둘러보기</a><a href="#about">소개</a></div>}
 <main><section className="hero"><div className="hero-copy"><span>공간 큐레이션</span><h1>{heroTitle}</h1><p>{data.settings.heroDescription}</p><button onClick={()=>document.getElementById('projects')?.scrollIntoView({behavior:'smooth'})}>공간 속 가구 보기 <ArrowUpRight size={17}/></button></div><div className="hero-carousel"><div className="hero-image" onPointerDown={e=>{touchStart.current=e.clientX;e.currentTarget.setPointerCapture(e.pointerId)}} onPointerUp={e=>{if(touchStart.current===null||heroSlides.length<2)return;const distance=e.clientX-touchStart.current;if(Math.abs(distance)>45)setHeroIndex(index=>(index+(distance<0?1:-1)+heroSlides.length)%heroSlides.length);touchStart.current=null}} onPointerCancel={()=>{touchStart.current=null}}><div className="hero-track">{heroSlides.length?heroSlides.map(({project,image,url},index)=><div className={`hero-slide ${index===heroIndex?'active':''}`} aria-hidden={index!==heroIndex} key={`${project.id}-${image?.id||'cover'}`}><img src={url} alt={image?.alt||project.title} draggable={false} onError={e=>{if(!e.currentTarget.src.endsWith('/interior-living.png'))e.currentTarget.src='/interior-living.png'}}/></div>):<div className="hero-slide active"><img src="/interior-living.png" alt="메인 공간" draggable={false}/></div>}</div><div className="hero-note"><i></i><div><b>이번 주의 공간</b><span>{heroSlides[heroIndex]?.project.title||data.projects[0]?.title}</span></div></div></div>{heroSlides.length>1&&<div className="hero-dots" aria-label="대표 공간 선택">{heroSlides.map((slide,index)=><button key={`${slide.project.id}-${slide.image?.id||'cover'}`} className={index===heroIndex?'on':''} aria-label={`${index+1}번째 공간`} onClick={()=>setHeroIndex(index)}/>)}</div>}</div></section>
 <section className="categories"><div className="filter-group"><strong>공간별</strong><div><button className={category==='all'?'on':''} onClick={()=>setCategory('all')}>전체</button>{data.categories.map(c=><button key={c.id} className={category===c.id?'on':''} onClick={()=>setCategory(c.id)}>{c.name}</button>)}</div></div></section>
 <section id="projects" className="projects"><div className="section-head"><div><span>추천 공간</span><h2>{query?`“${query}” 검색 결과`:'당신을 위한 공간'}</h2></div><p>{filtered.length}개의 큐레이션</p></div><div className="grid">{filtered.map((p,i)=><article key={p.id} className={`card card-${i}`} onClick={()=>setSelected(p)}><div className="card-img"><img src={p.images[0]?.url} alt={p.images[0]?.alt||p.title}/><div className="card-badges"><span className="badge">{data.categories.find(c=>c.id===p.categoryId)?.name}</span><span className="badge mood-badge">{projectMood(p)}</span></div><button aria-label={`${p.title} 자세히 보기`}><ArrowUpRight/></button></div><div className="card-info"><span>{/^CURATED SPACES?$/i.test(p.eyebrow||'')?'추천 공간':p.eyebrow||'추천 공간'}</span><h3>{p.title}</h3><p>{p.subtitle}</p><div className="mini-products">{p.images.flatMap(x=>x.hotspots).slice(0,3).map(h=><i key={h.id}>{h.name}</i>)}</div></div></article>)}</div>{!filtered.length&&<div className="empty"><Search/><h3>조건에 맞는 공간이 없어요</h3><p>다른 필터를 선택해보세요.</p></div>}</section>
 <section id="about" className="manifesto"><h2>가구를 고르는 일이<br/>공간을 상상하는 일부터 시작되도록.</h2><p>한 장의 공간에서 시작해<br/>당신다운 집을 완성해보세요.</p></section></main><Footer s={data.settings}/></div>}
function Brand({s}:{s:Partial<Settings>}){return <a className="logo" href="/">{s.logoUrl?<img src={s.logoUrl} alt={s.siteName}/>:<>{s.siteName||'MORUM'}<span>.</span></>}</a>}
function Footer({s}:{s:Partial<Settings>}){return <footer><Brand s={s}/><div className="footer-copy"><p>{s.footerText}</p><p className="footer-contact">제휴 및 문의: n_work_@naver.com</p></div><small>© 2026 {s.siteName}. 모든 권리 보유.</small></footer>}
function Detail({project,category,settings,back}:{project:Project;category:string;settings:Partial<Settings>;back:()=>void}){const images=[...project.images].sort((a,b)=>a.order-b.order);const [image,setImage]=useState<RoomImage>(images[0]);const [active,setActive]=useState<Hotspot|null>(null);const [anchor,setAnchor]=useState({left:0,top:0,bottom:0});return <div className="detail"><header><button className="back" onClick={back}><ChevronLeft/> 돌아가기</button><Brand s={settings}/><div className="detail-actions"><span>{category}</span><button><ExternalLink size={17}/> 공유</button></div></header><main><div className="detail-title"><span>{project.eyebrow}</span><h1>{project.title}</h1><p>{project.subtitle}</p></div><div className="scene"><img src={image.url} alt={image.alt}/>{image.hotspots.map((h,i)=><button key={h.id} style={{left:h.x+'%',top:h.y+'%',background:h.color,width:h.size,height:h.size}} className={'hotspot '+(active?.id===h.id?'active':'')} onClick={e=>{if(active?.id===h.id)return setActive(null);const rect=e.currentTarget.getBoundingClientRect();setAnchor({left:rect.left+rect.width/2,top:rect.top,bottom:rect.bottom});setActive(h)}}><span>{i+1}</span></button>)}</div>{active&&<ProductPopup product={active} anchor={anchor} close={()=>setActive(null)}/>} {images.length>1&&<div className="image-thumbs">{images.map((x,i)=><button className={x.id===image.id?'on':''} onClick={()=>{setImage(x);setActive(null)}} key={x.id}><img src={x.url}/><span>{i+1}</span></button>)}</div>}<aside className="content-notice" aria-label="AI 이미지 및 수수료 안내"><strong>안내</strong><p>이 페이지의 공간 이미지는 AI로 제작된 참고 이미지이며, 실제 제품의 색상·크기·비율·배치는 이미지와 다를 수 있습니다.<br/>정확한 제품 정보는 구매 페이지의 상세 정보를 확인해주세요.<br/>오늘의집 제품은 오늘의집 큐레이터 활동의 일환으로, 구매 시 이에 따른 일정액의 수수료를 제공받습니다.</p></aside>
 <section className="used"><div className="section-head"><div><span>공간 속 제품</span><h2>이 공간에 사용된 제품</h2></div><p>{image.hotspots.length}개의 제품</p></div><div className="product-list">{image.hotspots.map((h,i)=><a href={h.url} target="_blank" rel="noreferrer" key={h.id}><ProductThumbnail hotspot={h} roomImage={image.url} index={i}/><div><small>{h.brand}</small><b>{h.name}</b><p>{h.description}</p><strong>{h.price}</strong></div><ArrowUpRight className="product-arrow"/></a>)}</div></section>{project.videoUrl&&<a className="video" href={project.videoUrl} target="_blank" rel="noreferrer"><div><span>관련 이야기</span><h2>이 공간이 완성되는 과정을<br/>영상으로 만나보세요.</h2></div><button><Play fill="currentColor"/> 관련 영상 보기</button></a>}</main><Footer s={settings}/></div>}
function ProductThumbnail({hotspot,roomImage,index}:{hotspot:Hotspot;roomImage:string;index:number}){const productImage=productImageUrl(hotspot),position=cropPosition(hotspot);return <div className="product-thumb"><img className={productImage?'product-image':'hotspot-crop'} src={productImage||roomImage||'/interior-living.png'} alt={`${hotspot.name} 제품 위치`} style={productImage?undefined:{objectPosition:position}} onError={e=>{const fallback=roomImage||'/interior-living.png',current=e.currentTarget.getAttribute('src');if(current!==fallback){e.currentTarget.src=fallback;e.currentTarget.className='hotspot-crop';e.currentTarget.style.objectPosition=position}else if(fallback!=='/interior-living.png')e.currentTarget.src='/interior-living.png'}}/><span>{String(index+1).padStart(2,'0')}</span></div>}
function ProductPopup({product,anchor,close}:{product:Hotspot;anchor:{left:number;top:number;bottom:number};close:()=>void}){const popupTop=anchor.bottom+14+280>window.innerHeight?Math.max(12,anchor.top-294):anchor.bottom+14;return createPortal(<><button className="product-pop-backdrop" aria-label="제품 팝업 닫기" onClick={close}/><div className="product-pop product-pop-portal" role="dialog" aria-modal="true" aria-label={`${product.name} 제품 정보`} style={{left:`clamp(16px, ${anchor.left-155}px, calc(100vw - 326px))`,top:popupTop}}><button className="pop-x" aria-label="닫기" onClick={close}><X size={18}/></button><small>{product.brand}</small><b>{product.name}</b><p>{product.description}</p><strong>{product.price}</strong><a href={product.url} target="_blank" rel="noreferrer">구매하러 가기 <ArrowUpRight size={16}/></a></div></>,document.body)}
