'use client';
import { useEffect,useMemo,useState } from 'react';
import { Search,Menu,X,ArrowUpRight,Play,ExternalLink,ChevronLeft,Wrench } from 'lucide-react';
import type { Category,Project,RoomImage,Hotspot,Settings } from '@/lib/types';
type PublicData={categories:Category[];projects:Project[];settings:Omit<Settings,'adminId'|'adminPasswordHash'>};
export default function Home(){const [data,setData]=useState<PublicData|null>(null);const [category,setCategory]=useState('all');const [query,setQuery]=useState('');const [selected,setSelected]=useState<Project|null>(null);const [mobile,setMobile]=useState(false);
 useEffect(()=>{fetch('/api/public',{cache:'no-store'}).then(r=>r.json()).then(setData)},[]);
 const filtered=useMemo(()=>data?.projects.filter(p=>(category==='all'||p.categoryId===category)&&(!query||`${p.title} ${p.subtitle} ${p.images.flatMap(i=>i.hotspots.map(h=>`${h.name} ${h.brand} ${h.description}`)).join(' ')}`.toLowerCase().includes(query.toLowerCase())))||[],[data,category,query]);
 if(!data)return <div className="loading"><span></span><p>공간을 준비하고 있습니다</p></div>;
 if(data.settings.serviceStatus==='maintenance')return <div className="status-screen"><Brand s={data.settings}/><div className="status-mark"><Wrench/></div><span>MAINTENANCE</span><h1>현재 사이트 점검 중입니다.</h1><p>더 나은 공간 경험을 위해 잠시 정비하고 있습니다.<br/>빠른 시일 내에 다시 찾아뵙겠습니다.</p></div>;
 if(selected)return <Detail project={selected} category={data.categories.find(c=>c.id===selected.categoryId)?.name||''} settings={data.settings} back={()=>setSelected(null)}/>;
 return <div className="site"><header><Brand s={data.settings}/><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="공간이나 제품을 검색해보세요"/>{query&&<button onClick={()=>setQuery('')}><X size={16}/></button>}</div><nav><a href="#projects">공간 둘러보기</a><a href="#about">소개</a></nav><button className="mobile-menu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header>{mobile&&<div className="mobile-nav"><a href="#projects">공간 둘러보기</a><a href="#about">소개</a></div>}
 <main><section className="hero"><div className="hero-copy"><span>INTERIOR CURATION</span><h1>{data.settings.heroTitle}</h1><p>{data.settings.heroDescription}</p><button onClick={()=>document.getElementById('projects')?.scrollIntoView({behavior:'smooth'})}>공간 둘러보기 <ArrowUpRight size={17}/></button></div><div className="hero-image"><img src={data.projects[0]?.images[0]?.url||'/interior-living.png'} alt="메인 공간"/><div className="hero-note"><i></i><div><b>이번 주의 공간</b><span>{data.projects[0]?.title}</span></div></div></div></section>
 <section className="categories"><span>공간별 큐레이션</span><div><button className={category==='all'?'on':''} onClick={()=>setCategory('all')}>전체</button>{data.categories.map(c=><button key={c.id} className={category===c.id?'on':''} onClick={()=>setCategory(c.id)}>{c.name}</button>)}</div></section>
 <section id="projects" className="projects"><div className="section-head"><div><span>CURATED SPACES</span><h2>{query?`“${query}” 검색 결과`:'당신을 위한 공간'}</h2></div><p>{filtered.length}개의 큐레이션</p></div><div className="grid">{filtered.map((p,i)=><article key={p.id} className={`card card-${i}`} onClick={()=>setSelected(p)}><div className="card-img"><img src={p.images[0]?.url} alt={p.images[0]?.alt||p.title}/><span className="badge">{data.categories.find(c=>c.id===p.categoryId)?.name}</span><button><ArrowUpRight/></button></div><div className="card-info"><span>{p.eyebrow}</span><h3>{p.title}</h3><p>{p.subtitle}</p><div className="mini-products">{p.images.flatMap(x=>x.hotspots).slice(0,3).map(h=><i key={h.id}>{h.name}</i>)}</div></div></article>)}</div>{!filtered.length&&<div className="empty"><Search/><h3>검색 결과가 없어요</h3><p>다른 키워드로 찾아보세요.</p></div>}</section>
 <section id="about" className="manifesto"><span>CURATION, NOT CATALOG</span><h2>가구를 고르는 일이<br/>공간을 상상하는 일부터 시작되도록.</h2><p>한 장의 공간에서 시작해<br/>당신다운 집을 완성해보세요.</p></section></main><Footer s={data.settings}/></div>}
function Brand({s}:{s:Partial<Settings>}){return <a className="logo" href="/">{s.logoUrl?<img src={s.logoUrl} alt={s.siteName}/>:<>{s.siteName||'MORUM'}<span>.</span></>}</a>}
function Footer({s}:{s:Partial<Settings>}){return <footer><Brand s={s}/><p>{s.footerText}</p><small>© 2026 {s.siteName}. ALL RIGHTS RESERVED.</small></footer>}
function Detail({project,category,settings,back}:{project:Project;category:string;settings:Partial<Settings>;back:()=>void}){const images=[...project.images].sort((a,b)=>a.order-b.order);const [image,setImage]=useState<RoomImage>(images[0]);const [active,setActive]=useState<Hotspot|null>(null);return <div className="detail"><header><button className="back" onClick={back}><ChevronLeft/> 돌아가기</button><Brand s={settings}/><div className="detail-actions"><span>{category}</span><button><ExternalLink size={17}/> 공유</button></div></header><main><div className="detail-title"><span>{project.eyebrow}</span><h1>{project.title}</h1><p>{project.subtitle}</p></div><div className="scene"><img src={image.url} alt={image.alt}/>{image.hotspots.map((h,i)=><button key={h.id} style={{left:h.x+'%',top:h.y+'%',background:h.color,width:h.size,height:h.size}} className={'hotspot '+(active?.id===h.id?'active':'')} onClick={()=>setActive(active?.id===h.id?null:h)}><span>{i+1}</span></button>)}{active&&<div className="product-pop" style={{left:`clamp(16px, ${active.x}%, calc(100% - 330px))`,top:`clamp(80px, ${active.y+5}%, calc(100% - 170px))`}}><button className="pop-x" onClick={()=>setActive(null)}><X size={16}/></button><small>{active.brand}</small><b>{active.name}</b><p>{active.description}</p><strong>{active.price}</strong><a href={active.url} target="_blank" rel="noreferrer">구매하러 가기 <ArrowUpRight size={16}/></a></div>}</div>{images.length>1&&<div className="image-thumbs">{images.map((x,i)=><button className={x.id===image.id?'on':''} onClick={()=>{setImage(x);setActive(null)}} key={x.id}><img src={x.url}/><span>{i+1}</span></button>)}</div>}
 <section className="used"><div className="section-head"><div><span>SHOP THE LOOK</span><h2>이 공간에 사용된 제품</h2></div><p>{image.hotspots.length}개의 제품</p></div><div className="product-list">{image.hotspots.map((h,i)=><a href={h.url} target="_blank" rel="noreferrer" key={h.id}><div className="product-thumb"><img src={image.url}/><span>{String(i+1).padStart(2,'0')}</span></div><div><small>{h.brand}</small><b>{h.name}</b><p>{h.description}</p><strong>{h.price}</strong></div><ArrowUpRight className="product-arrow"/></a>)}</div></section>{project.videoUrl&&<a className="video" href={project.videoUrl} target="_blank" rel="noreferrer"><div><span>RELATED STORY</span><h2>이 공간이 완성되는 과정을<br/>영상으로 만나보세요.</h2></div><button><Play fill="currentColor"/> 관련 영상 보기</button></a>}</main><Footer s={settings}/></div>}
